### ISSUE TITLE
Remove deep import of angular/compiler to be able to run with Angular2 RC6

### ISSUE THREAD

**Issue by jerkly** [afrad/angular2-websocket#36]
From http://angularjs.blogspot.ru/2016/09/angular-2-rc6_1.html

> If you’ve previously deep imported from @angular packages (e.g. @angular/core/src/foo/bar), note that this no longer works in RC6. Always import from the root of a package (eg, @angular/core). Deep imports are private APIs, and likely to change.

Right now `angular2-websocket` is starting with errors.

From `angular2-websocket.ts`
```typescript
...
import {isPresent, isString, isArray,isFunction} from '@angular/compiler/src/facade/lang';
...
```

Stacktrace from browser
```javascript
(index):43 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:5005/vendor/angular2-websocket/angular2-websocket.js:13:14)
	    at eval (http://localhost:5005/vendor/angular2-websocket/angular2-websocket.js:213:4)
	    at eval (http://localhost:5005/vendor/angular2-websocket/angular2-websocket.js:214:3)
	Evaluating http://localhost:5005/vendor/@angular/compiler/bundles/compiler.umd.js/src/facade/lang
	Evaluating http://localhost:5005/vendor/angular2-websocket/angular2-websocket.js
...
```

**Comment by afrad** [comment]
merged
